#!/bin/bash

# @file create-memento-nginx-config
#
# Project Clearwater - IMS in the Cloud
# Copyright (C) 2014 Metaswitch Networks Ltd
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version, along with the "Special Exception" for use of
# the program along with SSL, set forth below. This program is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details. You should have received a copy of the GNU General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
# The author can be reached by email at clearwater@metaswitch.com or by
# post at Metaswitch Networks Ltd, 100 Church St, Enfield EN2 6BQ, UK
#
# Special Exception
# Metaswitch Networks Ltd  grants you permission to copy, modify,
# propagate, and distribute a work formed by combining OpenSSL with The
# Software, or a work derivative of such a combination, even if such
# copying, modification, propagation, or distribution would otherwise
# violate the terms of the GPL. You must comply with the GPL in all
# respects for all of the code used other than OpenSSL.
# "OpenSSL" means OpenSSL toolkit software distributed by the OpenSSL
# Project and licensed under the OpenSSL Licenses, or a work based on such
# software and licensed under the OpenSSL Licenses.
# "OpenSSL Licenses" means the OpenSSL License and Original SSLeay License
# under which the OpenSSL Project distributes the OpenSSL toolkit software,
# as those licenses appear in the file LICENSE-OPENSSL.

# This file creates an nginx config file for Memento.

. /etc/clearwater/config

if [ -n "$home_domain" ]
then
  if [ -z $memento_hostname ]
  then
    memento_hostname="memento.$home_domain"
  fi

  # Create the config file, using the memento_hostname we've got from
  # /etc/clearwater/config
  temp_file=$(mktemp memento.nginx.XXXXXXXX)
  site_file=/etc/nginx/sites-available/memento
  enabled_file=/etc/nginx/sites-enabled/memento
  cat > $temp_file << EOF
upstream http_backend {
        server localhost:11888;

        # The minimum number of idle connections to keep alive to the backend.
        keepalive 16;
}

server {
        listen       [::]:443 ipv6only=off;
        server_name  $memento_hostname;

        ssl                  on;
        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        ssl_session_timeout  5m;

        ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers  ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS;
        ssl_prefer_server_ciphers   on;

        # <memento_hostname>/ping tests memento through nginx. localhost/ping
        # is used to just test nginx. This is defined in the ping site which
        # is installed with the clearwater-nginx package.
        location /ping {
                proxy_pass http://http_backend;
                proxy_http_version 1.1;

                # The client may have instructed the server to close the
                # connection - do not forward this upstream.
                proxy_set_header Connection "";

                # Do not forward any NGV-API-Key header upstream.
                proxy_set_header NGV-API-Key "";
        }

        location /org.projectclearwater.call-list {
                proxy_pass http://http_backend;
                proxy_http_version 1.1;

                # The client may have instructed the server to close the
                # connection - do not forward this upstream.
                proxy_set_header Connection "";

                # Do not forward any NGV-API-Key header upstream.
                proxy_set_header NGV-API-Key "";

                gzip on;
                gzip_types *;
        }
}

server {
        # No ipv6only=off needed - it's covered by the listen
        # declaration for port 80 in ./ping
        listen       [::]:80;
        server_name $memento_hostname;
        return 301 https://\$host\$request_uri;
}
EOF

  if ! diff $temp_file $enabled_file > /dev/null 2>&1
  then
    # Update the site file
    mv $temp_file $site_file

    # Enable the memento nginx site
    if ( nginx_ensite memento > /dev/null )
    then
      service nginx stop
    fi
  else
    rm $temp_file
  fi
fi
