#!/bin/bash

# @file create-memento-nginx-config
#
# Copyright (C) Metaswitch Networks 2015
# If license terms are provided to you in a COPYING file in the root directory
# of the source code repository by which you are accessing this code, then
# the license outlined in that COPYING file applies to your use.
# Otherwise no rights are granted except for those provided to you by
# Metaswitch Networks in a separate written agreement.

# This file creates an nginx config file for Memento.

. /etc/clearwater/config

if [ -n "$home_domain" ]
then
  if [ -z $memento_hostname ]
  then
    memento_hostname="memento.$home_domain"
  fi

  # Create the config file, using the memento_hostname we've got from
  # /etc/clearwater/config
  temp_file=$(mktemp memento.nginx.XXXXXXXX)
  site_file=/etc/nginx/sites-available/memento
  enabled_file=/etc/nginx/sites-enabled/memento
  cat > $temp_file << EOF
upstream http_backend {
        server ${local_ip}:11888;

        # The minimum number of idle connections to keep alive to the backend.
        keepalive 16;
}

server {
        listen       [::]:443 ipv6only=off;
        server_name  $memento_hostname;

        ssl                  on;
        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        ssl_session_timeout  5m;

        ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers  ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS;
        ssl_prefer_server_ciphers   on;

        # <memento_hostname>/ping tests memento through nginx. localhost/ping
        # is used to just test nginx. This is defined in the ping site which
        # is installed with the clearwater-nginx package.
        location /ping {
                proxy_pass http://http_backend;
                proxy_http_version 1.1;

                # The client may have instructed the server to close the
                # connection - do not forward this upstream.
                proxy_set_header Connection "";

                # Do not forward any NGV-API-Key header upstream.
                proxy_set_header NGV-API-Key "";
        }

        location /org.projectclearwater.call-list {
                proxy_pass http://http_backend;
                proxy_http_version 1.1;

                # The client may have instructed the server to close the
                # connection - do not forward this upstream.
                proxy_set_header Connection "";

                # Do not forward any NGV-API-Key header upstream.
                proxy_set_header NGV-API-Key "";

                gzip on;
                gzip_types *;
        }
}

server {
        # No ipv6only=off needed - it's covered by the listen
        # declaration for port 80 in ./ping
        listen       [::]:80;
        server_name $memento_hostname;
        return 301 https://\$host\$request_uri;
}
EOF

  if ! diff $temp_file $enabled_file > /dev/null 2>&1
  then
    # Update the site file
    mv $temp_file $site_file

    # Enable the memento nginx site
    if ( nginx_ensite memento > /dev/null )
    then
      service nginx stop
    fi
  else
    rm $temp_file
  fi
fi
