#!/bin/bash

# @file memento_disk_usage
#
# Copyright (C) Metaswitch Networks 2017
# If license terms are provided to you in a COPYING file in the root directory
# of the source code repository by which you are accessing this code, then
# the license outlined in that COPYING file applies to your use.
# Otherwise no rights are granted except for those provided to you by
# Metaswitch Networks in a separate written agreement.

. /usr/share/clearwater/bin/memento-disk-usage-functions

# Utility function for accessing the logger
function log() {
  logger -s -p cron.$1 -t "Memento Disk Usage" "$2"
}

# Load global settings
. /etc/clearwater/config
if [[ -z $memento_disk_limit ]]
then
  log info "No disk limit configured, using 20% of the disk"
  memento_disk_limit="20%"
fi

# Calculate the total disk available in kilobytes
total_avail=$(memento_get_total_avail)

# Retrieve the current usage
current_use=$(memento_get_current_use)

# Parse out the units from the config file's value
unit=${memento_disk_limit: -1} # The last character
if [[ $unit =~ [0-9] ]]
then
  # No unit given, assume bytes
  unit="b"
  max_use=$memento_disk_limit
else
  max_use=${memento_disk_limit%?} # Everything but the last character
fi

# Convert units to kilobytes
case $unit in
  b)
    max_use=$(( $max_use / 1024 ))
    ;;
  k)
    max_use=$(( $max_use ))
    ;;
  M)
    max_use=$(( $max_use * 1024 ))
    ;;
  G)
    max_use=$(( $max_use * 1024 * 1024 ))
    ;;
  %)
    if (( $max_use < 0 )) || (( $max_use > 100 ))
    then
      log error "Invalid percentage ($max_use%), using 20% of disk as limit"
      max_use=20
    fi
    max_use=$(( $total_avail * $max_use / 100 ))
    ;;
  *)
    # Unrecognised unit, use 20% of disk capacity
    log error "Unrecognised unit ($unit), using 20% of disk as limit"
    max_use=$(( $total_avail / 5 ))
    ;;
esac

log info "Applying limits, current use = ${current_use}k, limit = ${max_use}k"

# Compare the current usage to the limit
if (( $current_use > $max_use ))
then
  log warning "Disk usage is over limit, deleting snapshots"
  nodetool clearsnapshot memento

  # Recheck usage
  current_use=$(memento_get_current_use)

  log info "After deleting snapshots: current_use = ${current_use}k, limit = ${max_use}k"

  if (( $current_use > $max_use ))
  then
    log warning "Disk usage still over capacity, truncating database"
    echo "USE memento ;
          TRUNCATE call_lists ;" | cqlsh
    nodetool clearsnapshot memento
  fi

  current_use=$(memento_get_current_use)

  log info "New disk usage is ${current_use}k"
fi

# Update the temporary file containing the current usage
echo $current_use > $MEMENTO_DISK_USAGE_FILE
